name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when pushing to main
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html
        run: |
          pandoc README.md -o index.html --standalone --metadata title="Adam Duboczky - Resume"

      - name: Setup GitHub Pages
        run: |
          mkdir public
          mv index.html public/
      
      - name: Upload to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          folder: public
