name: Deploy README to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when pushing to main
  workflow_dispatch:  # Allows manual execution

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert README.md to index.html
        run: |
          pandoc README.md -o index.html --standalone --metadata title="Adam Duboczky - Resume"

      - name: Upload Artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
